ARG DOCKER_BASE_IMAGE
FROM $DOCKER_BASE_IMAGE
ARG WHEEL_FILES_PATH
ARG REPO_SHORT

LABEL org.opencontainers.image.source=https://github.com/tenstorrent/${REPO_SHORT}
LABEL org.opencontainers.image.description=${REPO_SHORT}
LABEL org.opencontainers.image.licenses=Apache-2.0

ENV VLLM_TARGET_DEVICE="empty"

RUN --mount=type=bind,source=$WHEEL_FILES_PATH,target=/wheels \
    ls -la /wheels && \
    # Set up pyenv environment explicitly
    export PYENV_ROOT="$HOME/.pyenv" && \
    export PATH="$PYENV_ROOT/bin:$PATH" && \
    eval "$(pyenv init -)" && \
    for wheel in /wheels/*.whl; do \
      pip install "$wheel"; \
      if [[ "$wheel" == *"pjrt_"* ]]; then \
        tt-forge-install; \
      fi; \
    done && \
    pip cache purge
