

name: "Create RC branch"
description: "Create RC branch"
inputs:
  repo:
    description: "Repo name"
    required: true
  draft:
    description: "Draft release"
    required: false
    default: false
  GH_TOKEN:
    description: "GitHub token"
    required: true
  commit:
    description: "Commit hash"
    required: true
  new_version_tag:
    description: "New version tag"
    required: true


runs:
  using: "composite"
  steps:

    - name: Checkout target repo
      if: ${{  inputs.draft == 'false' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        token: ${{ inputs.GH_TOKEN }}
        ref: ${{ inputs.branch }}
        fetch-depth: 0

    - name: Create/Get Release Branch
      shell: bash
      id: get-release-branch
      run: |
        git clean -xdf
        if [ $(git tag -l "${{ inputs.new_version_tag }}") ]; then
          echo "Tag ${{ inputs.new_version_tag }} already exists"
        else
          git tag ${{ inputs.new_version_tag }} ${{ inputs.commit }}
          git push origin --tags
        fi


    # Recheckout forge repo to fix side effects for clean up job
    - uses: actions/checkout@v4
      if: ${{  inputs.draft == 'false' }}
