
name: "Create docs"
description: "Creates a release doc for all frontend and cats them to one single file"
inputs:
  owner:
    description: "Repo's owner name"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Build Hardware Compatibility Matrix 
      shell: bash
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt