
name: "Set Release Facts"
description: "Set Release Facts"
inputs:
  repo:
    description: "Repo name"
    required: false
  release_type:
    description: "Release type"
    required: false
  draft:
    description: "Draft release"
    required: false
  new_version_tag:
    description: "New version tag for wheel"
    required: false
    default: ''
  branch:
    description: "Branch name"
    required: false
    default: ''
  latest_branch_commit:
    description: "Latest branch commit"
    required: false
    default: ''

outputs:
  workflow:
    description: "Workflow name"
    value: ${{ steps.set-manifest.outputs.workflow }}
  artifact_download_glob:
    description: "Artifact download glob"
    value: ${{ steps.set-manifest.outputs.artifact_download_glob }}
  artifact_cleanup_file_glob:
    description: "Artifact cleanup file glob"
    value: ${{ steps.set-manifest.outputs.artifact_cleanup_file_glob }}
  artifact_cleanup_folder_glob:
    description: "Artifact cleanup folder glob"
    value: ${{ steps.set-manifest.outputs.artifact_cleanup_folder_glob }}
  workflow_result_in_job:
    description: "Workflow result in job"
    value: ${{ steps.set-manifest.outputs.workflow_result_in_job }}
  repo_short:
    description: "Repo short name without owner"
    value: ${{ steps.set-manifest.outputs.repo_short }}
  new_version_tag:
    description: "New version tag for wheel"
    value: ${{ steps.set-manifest.outputs.new_version_tag }}
  gh_new_version_tag:
    description: "New version tag for GitHub release"
    value: ${{ steps.set-manifest.outputs.gh_new_version_tag }}
  pip_wheel_names:
    description: "Names of pip wheels"
    value: ${{ steps.set-manifest.outputs.pip_wheel_names }}
  pip_wheel_deps_names:
    description: "Names of pip wheel dependencies"
    value: ${{ steps.set-manifest.outputs.pip_wheel_deps_names }}
  all_repos:
    description: "All repos that are allowed to release"
    value: ${{ steps.set-manifest.outputs.all_repos }}
  build_release_tag:
    description: "Build release tag"
    value: ${{ steps.set-manifest.outputs.build_release_tag }}
  build_release_find_workflow_branch:
    description: "Build find workflow branch"
    value: ${{ steps.set-manifest.outputs.build_release_find_workflow_branch }}
  workflow_allow_failed:
    description: "Return run even if workflow has failed"
    value: ${{ steps.set-manifest.outputs.workflow_allow_failed }}
  build_release_latest_branch_commit:
    description: "Build release latest branch commit"
    value: ${{ steps.set-manifest.outputs.build_release_latest_branch_commit }}
  major_version:
    description: "Major version"
    value: ${{ steps.set-manifest.outputs.major_version }}
  minor_version:
    description: "Minor version"
    value: ${{ steps.set-manifest.outputs.minor_version }}
  prerelease:
    description: "Prerelease release"
    value: ${{ steps.set-manifest.outputs.prerelease }}
  repo_full:
    description: "Repo name with full path"
    value: ${{ steps.set-manifest.outputs.repo_full }}
  draft:
    description: "Draft release"
    value: ${{ steps.set-manifest.outputs.draft }}
  make_latest:
    description: "Make release latest"
    value: ${{ steps.set-manifest.outputs.make_latest }}
  ignore_artifacts:
    description: "Ignore artifacts"
    value: ${{ steps.set-manifest.outputs.ignore_artifacts }}
  skip_model_compatible_table:
    description: "Skip model compatible table"
    value: ${{ steps.set-manifest.outputs.skip_model_compatible_table }}
  skip_docker_build:
    description: "Skip docker build"
    value: ${{ steps.set-manifest.outputs.skip_docker_build }}
  git_log_fail_on_error:
    description: "Fail on error"
    value: ${{ steps.set-manifest.outputs.git_log_fail_on_error }}
  test_demo_filter:
    description: "Test demo filter"
    value: ${{ steps.set-manifest.outputs.test_demo_filter }}
  test_demo_wait:
    description: "Test demo wait"
    value: ${{ steps.set-manifest.outputs.test_demo_wait }}
  python_version:
    description: "Python version"
    value: ${{ steps.set-manifest.outputs.python_version }}
  test_perf_filter:
    description: "Test perf filter"
    value: ${{ steps.set-manifest.outputs.test_perf_filter }}
  test_perf_sh_runner:
    description: "Test perf sh runner"
    value: ${{ steps.set-manifest.outputs.test_perf_sh_runner }}
  test_perf:
    description: "Test perf"
    value: ${{ steps.set-manifest.outputs.test_perf }}
  basic_tests_runner_filter:
    description: "Basic tests runner filter"
    value: ${{ steps.set-manifest.outputs.basic_tests_runner_filter }}
  uplift_artifacts_by_commit:
    description: "Uplift artifacts by commit"
    value: ${{ steps.set-manifest.outputs.uplift_artifacts_by_commit }}
  artifact_name_prefix:
    description: "Artifact name prefix"
    value: ${{ steps.set-manifest.outputs.artifact_name_prefix }}
  schedule_nightly_repos:
    description: "List of repos that are allowed to release nightly on a schedule"
    value: ${{ steps.set-manifest.outputs.schedule_nightly_repos }}
  schedule_rc_stable_update_repos:
    description: "List of repos that are allowed to update RC and Stable releases on a schedule"
    value: ${{ steps.set-manifest.outputs.schedule_rc_stable_update_repos }}

runs:
  using: "composite"
  steps:
    - name: Set Releaser manifest
      id: set-manifest
      shell: bash
      run: |
        # Set release facts based on repo
        set -e
        source .version

        # All Repo Defaults

        # Repository name from input parameter
        repo="${{ inputs.repo }}"
        # Repository name without the "tenstorrent/" prefix
        repo_short="${repo#tenstorrent/}"
        # Full repository name with "tenstorrent/" prefix
        repo_full="tenstorrent/${repo_short}"
        # List of all repos that will release nightly on a schedule
        schedule_nightly_repos='tenstorrent/tt-forge-fe tenstorrent/tt-mlir tenstorrent/tt-forge'
        # List of repos that are allowed to update RC and Stable releases on a schedule
        schedule_rc_stable_update_repos='tenstorrent/tt-forge-fe tenstorrent/tt-xla tenstorrent/tt-forge'
        # Allow workflow failures when finding build workflows
        workflow_allow_failed="false"
        # Branch to search for build workflows
        build_release_find_workflow_branch="${{ inputs.branch }}"
        # Latest commit on the branch for build releases
        build_release_latest_branch_commit="${{ inputs.latest_branch_commit }}"
        # Tag to use for build releases
        build_release_tag="${{ inputs.new_version_tag }}"
        # This is a prerelease (true for RC/nightly, false for stable)
        prerelease="true"
        # This is a draft release
        draft="${{ inputs.draft }}"
        # Mark this release as the latest
        make_latest="false"
        # Major version number from .version file
        major_version=$MAJOR
        # Minor version number from .version file
        minor_version=$MINOR
        # Ignore artifact processing in releases
        ignore_artifacts="false"
        # Skip generating model compatibility table
        skip_model_compatible_table="false"
        # Skip Docker build steps
        skip_docker_build="false"
        # Fail on git log errors during changelog generation
        git_log_fail_on_error="true"
        # Filter for which demo tests to run (empty = all)
        test_demo_filter=""
        # Run performance tests
        test_perf="false"
        # Run performance tests with shared CIv2 runner
        test_perf_sh_runner="false"
        # Filter for which performance tests to run (empty = all)
        test_perf_filter=""
        # Wait for demo tests to complete
        test_demo_wait="false"
        # Python version to use for builds and tests
        python_version="3.11"
        # Filter for which test runners to use for basic tests
        basic_tests_runner_filter="All"
        # Uplift artifacts by commit
        uplift_artifacts_by_commit="false"
        # Artifact name prefix for uplift artifacts by commit
        artifact_name_prefix=""

        # Tag & Release Defaults

        new_version_tag="${{ inputs.new_version_tag }}"

        # RC is not mentioned here since the defaults are enough
        if [[ "${{ inputs.release_type }}" == "stable" ]]; then
          prerelease="false"
          make_latest="true"
        elif [[ "${{ inputs.release_type }}" == "nightly" ]]; then
          new_version_tag="${VERSION}.dev$(date +"%Y%m%d")"
          workflow_allow_failed="true"
          build_release_find_workflow_branch="main"
        fi

        gh_new_version_tag="${new_version_tag}"
        build_release_tag="${new_version_tag}"


        # Repo Specific Defaults

        if [[ "${{ inputs.repo }}" =~ "tt-forge-fe" ]]; then
            workflow="On nightly"
            if [[ "${{ inputs.release_type }}" == "nightly" ]]; then
                workflow="On push"
            fi
            artifact_download_glob='*{wheel,test-reports}*'
            artifact_cleanup_file_glob='*{.json,benchmark_}*'
            workflow_result_in_job="fail-notify"
            pip_wheel_names="tt_forge_fe tt_tvm"
        elif [[ "${{ inputs.repo }}" =~ "tt-mlir" ]]; then
            workflow="schedule-nightly.yml"
            artifact_download_glob='*ttmlir-wheel*'
            pip_wheel_names="ttmlir"
            skip_model_compatible_table="true"
            skip_docker_build="true"
        elif [[ "${{ inputs.repo }}" =~ "tt-xla" ]]; then
            workflow="On nightly"
            if [[ "${{ inputs.release_type }}" == "nightly" ]]; then
                workflow="On push"
            fi
            artifact_name_prefix="xla-whl-release"
            artifact_download_glob='*{xla-whl-release,test-reports}*'
            pip_wheel_names="pjrt-plugin-tt"
            test_perf="true"
            uplift_artifacts_by_commit="true"
        elif [[ "${{ inputs.repo }}" =~ "tt-forge" ]]; then
            workflow="Daily Releaser"
            ignore_artifacts="true"
            pip_wheel_deps_names="pjrt-plugin-tt"
            pip_wheel_names="tt-forge"
            skip_model_compatible_table="true"
        fi


        # Testing Overrides

        # Different tags exist for integration testing for draft releases/test workflow. This is to guard against overwriting releases
        # We also can't use the draft style tag below since it won't work when we do a wheel re-version
        # REF: https://packaging.python.org/en/latest/discussions/versioning/#valid-version-numbers
        if [[ "${{ inputs.draft }}" == "true" ]]; then
            prerelease="true"
            # Wait for the demo test to complete only for draft releases and run only one test
            test_demo_filter="bge_m3"
            test_perf_filter="resnet"
            test_demo_wait="true"
            # Only run basic tests on n150 for draft releases until Civ2 capacity improves
            basic_tests_runner_filter="tt-ubuntu-2204-n150-stable"
            #test_perf_sh_runner="true"

            # null out the commit to so integration testing can pick up the arfiacts from the repo.
            # This is because this commit belongs to the tt-forge repo not where the artifacts are stored.
            # Since this is null, it will pick up the artifacts based on branch
            build_release_latest_branch_commit=""

            # Used in testing to pick up the arfiacts from the main branch.
            build_release_find_workflow_branch="main"

            # build_release_tag is a sanitized version tag for build_release action.
            # Tag sanitization only needs to happen for rc and stable release. See get-branches for more detail.

            if [[ "${{ inputs.release_type }}" == "stable" ]]; then
                new_version_tag="draft.${repo_short}.${new_version_tag}"
                set +e
                build_release_tag="$(echo "${new_version_tag}" | grep -oP '\d+\.\d+\.\d+')"
                set -e
                # Set to false for draft releases since we don't want to fail on error the RC & Stable Lifecycle test
                git_log_fail_on_error="false"
            elif [[ "${{ inputs.release_type }}" == "rc" ]]; then
                set +e
                build_release_tag="$(echo "${new_version_tag}" | grep -oP '\d+\.\d+\.\d+rc\d+')"
                set -e
                # Set to false for draft releases since we don't want to fail on error the RC & Stable Lifecycle test
                git_log_fail_on_error="false"
            else
                build_release_tag="${new_version_tag}"
            fi

            gh_new_version_tag="draft.${repo_short}.${build_release_tag}"
        fi

        echo "## Set Release Facts Outputs ##"
        echo "workflow=$workflow"
        echo "ignore_artifacts=$ignore_artifacts"
        echo "artifact_download_glob=$artifact_download_glob"
        echo "artifact_cleanup_file_glob=$artifact_cleanup_file_glob"
        echo "workflow_result_in_job=$workflow_result_in_job"
        echo "artifact_cleanup_folder_glob=$artifact_cleanup_folder_glob"
        echo "workflow_allow_failed=$workflow_allow_failed"
        echo "new_version_tag=$new_version_tag"
        echo "gh_new_version_tag=$gh_new_version_tag"
        echo "release_type=${{ inputs.release_type }}"
        echo "repo_short=$repo_short"
        echo "repo_full=$repo_full"
        echo "repo=$repo"
        echo "pip_wheel_names=$pip_wheel_names"
        echo "pip_wheel_deps_names=$pip_wheel_deps_names"
        echo "all_repos=$all_repos"
        echo "build_release_tag=$build_release_tag"
        echo "build_release_find_workflow_branch=$build_release_find_workflow_branch"
        echo "build_release_latest_branch_commit=$build_release_latest_branch_commit"
        echo "major_version=$major_version"
        echo "minor_version=$minor_version"
        echo "prerelease=$prerelease"
        echo "draft=$draft"
        echo "make_latest=$make_latest"
        echo "skip_model_compatible_table=$skip_model_compatible_table"
        echo "skip_docker_build=$skip_docker_build"
        echo "git_log_fail_on_error=$git_log_fail_on_error"
        echo "test_demo_filter=$test_demo_filter"
        echo "test_demo_wait=$test_demo_wait"
        echo "python_version=$python_version"
        echo "test_perf_filter=$test_perf_filter"
        echo "test_perf_sh_runner=$test_perf_sh_runner"
        echo "test_perf=$test_perf"
        echo "basic_tests_runner_filter=$basic_tests_runner_filter"
        echo "uplift_artifacts_by_commit=$uplift_artifacts_by_commit"
        echo "artifact_name_prefix=$artifact_name_prefix"
        echo "schedule_nightly_repos=$schedule_nightly_repos"
        echo "schedule_rc_stable_update_repos=$schedule_rc_stable_update_repos"

        # Set outputs
        echo "workflow=$workflow" >> $GITHUB_OUTPUT
        echo "ignore_artifacts=$ignore_artifacts" >> $GITHUB_OUTPUT
        echo "artifact_download_glob=$artifact_download_glob" >> $GITHUB_OUTPUT
        echo "artifact_cleanup_file_glob=$artifact_cleanup_file_glob" >> $GITHUB_OUTPUT
        echo "artifact_cleanup_folder_glob=$artifact_cleanup_folder_glob" >> $GITHUB_OUTPUT
        echo "workflow_result_in_job=$workflow_result_in_job" >> $GITHUB_OUTPUT
        echo "repo_short=$repo_short" >> $GITHUB_OUTPUT
        echo "repo_full=$repo_full" >> $GITHUB_OUTPUT
        echo "new_version_tag=$new_version_tag" >> $GITHUB_OUTPUT
        echo "gh_new_version_tag=$gh_new_version_tag" >> $GITHUB_OUTPUT
        echo "pip_wheel_names=$pip_wheel_names" >> $GITHUB_OUTPUT
        echo "pip_wheel_deps_names=$pip_wheel_deps_names" >> $GITHUB_OUTPUT
        echo "all_repos=$all_repos" >> $GITHUB_OUTPUT
        echo "build_release_tag=$build_release_tag" >> $GITHUB_OUTPUT
        echo "build_release_find_workflow_branch=$build_release_find_workflow_branch" >> $GITHUB_OUTPUT
        echo "workflow_allow_failed=$workflow_allow_failed" >> $GITHUB_OUTPUT
        echo "major_version=$major_version" >> $GITHUB_OUTPUT
        echo "minor_version=$minor_version" >> $GITHUB_OUTPUT
        echo "prerelease=$prerelease" >> $GITHUB_OUTPUT
        echo "draft=$draft" >> $GITHUB_OUTPUT
        echo "build_release_find_workflow_branch=$build_release_find_workflow_branch" >> $GITHUB_OUTPUT
        echo "build_release_latest_branch_commit=$build_release_latest_branch_commit" >> $GITHUB_OUTPUT
        echo "make_latest=$make_latest" >> $GITHUB_OUTPUT
        echo "skip_model_compatible_table=$skip_model_compatible_table" >> $GITHUB_OUTPUT
        echo "skip_docker_build=$skip_docker_build" >> $GITHUB_OUTPUT
        echo "git_log_fail_on_error=$git_log_fail_on_error" >> $GITHUB_OUTPUT
        echo "test_demo_filter=$test_demo_filter" >> $GITHUB_OUTPUT
        echo "test_demo_wait=$test_demo_wait" >> $GITHUB_OUTPUT
        echo "python_version=$python_version" >> $GITHUB_OUTPUT
        echo "test_perf_filter=$test_perf_filter" >> $GITHUB_OUTPUT
        echo "test_perf_sh_runner=$test_perf_sh_runner" >> $GITHUB_OUTPUT
        echo "test_perf=$test_perf" >> $GITHUB_OUTPUT
        echo "basic_tests_runner_filter=$basic_tests_runner_filter" >> $GITHUB_OUTPUT
        echo "uplift_artifacts_by_commit=$uplift_artifacts_by_commit" >> $GITHUB_OUTPUT
        echo "artifact_name_prefix=$artifact_name_prefix" >> $GITHUB_OUTPUT
        echo "schedule_nightly_repos=$schedule_nightly_repos" >> $GITHUB_OUTPUT
        echo "schedule_rc_stable_update_repos=$schedule_rc_stable_update_repos" >> $GITHUB_OUTPUT
