
name: "Check Release Branches"
description: "Check Release Branches"
inputs:
  repo:
    description: "Repo name"
    required: true

outputs:
  json_results:
    description: 'JSON results'
    value: ${{ steps.get-release-branches.outputs.json_results }}

runs:
  using: "composite"
  steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        token: ${{ env.GH_TOKEN }}
        fetch-depth: 0
    - name: Get Release Branches
      id: get-release-branches
      shell: bash
      run: |
        set -x
        # Get the latest release branches sorted by date in ascending order
        release_branches=$(git for-each-ref refs/remotes/origin/ --format='%(refname:short)' | grep -oP '(?<=origin\/)release-\d+\.\d+$' | xargs)
        json_results="[]"
        for branch in $release_branches; do
          git tag --sort=-creatordate --contains $branch
          current_release_tag=$(git describe --tags $(git rev-list --branches=$branch --tags --max-count=1)
          latest_tag_commit=$(git rev-list $current_release_tag --max-count=1)
          latest_branch_commit=$(git rev-list $branch --max-count=1)
          echo "Branch is $branch"
          echo "Current Release Tag is $current_release_tag"
          echo "Latest Tag Commit is $latest_tag_commit"
          echo "Latest Branch Commit is $latest_branch_commit"
          if [[ "$latest_tag_commit" != "$latest_branch_commit" ]]; then
            if [[ "$current_release_tag" =~ rc ]]; then
             # Bump RC version for release candidate branch
             IFS='.' read -r major minor rc rc_version <<< "$current_release_tag"
             new_version_tag="${major}.${minor}.${rc}.$((rc_version+1))"
            else
              # Bump Patch version for stable branch
              IFS='.' read -r major minor patch <<< "$current_release_tag"
              new_version_tag="${major}.${minor}.$((patch+1))"
            fi
            json_results=$(echo $json_results | jq -r --args branch $branch --arg new_version_tag $new_version_tag --arg latest_branch_commit $latest_branch_commit '. += [{
                "branch": "$branch",
                "new_version_tag": "$new_version_tag",
                "latest_branch_commit": "$latest_branch_commit"
            }]')
          fi
        done
        echo "json_results=$json_results" >> $GITHUB_OUTPUT



      
