name: Tag and release workflow
description: Create a tag and a release for it

inputs:
  wheel-artifact-name:
    required: true
    description: Name of the wheel's artifact that is getting released
  untar-wheel-artifact:
    required: false
    description: Flag that decides if you untar the artifact
    default: "false"

runs: 
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0

    - name: Add a tag
      id: add-tag
      shell: bash
      run: |
        TAG_NAME="nightly-$(date +'%Y%m%d')-${{ github.run_id }}-${{ github.run_attempt }}"
        git tag "$TAG_NAME"
        git push origin "$TAG_NAME"
        echo "tag-name=$TAG_NAME" >> "$GITHUB_OUTPUT"

    - name: Download wheel artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.wheel-artifact-name }}
        path: dist
    
    - name: Untar the wheel artifact
      if: ${{ inputs.untar-wheel-artifact }}
      shell: bash
      run: |
        cd dist
        tar xvf artifact.tar
        cp wheels/*.whl .
        cd ..

    - name: Get previous nightly tag and commit list
      id: commit-list
      shell: bash
      run: |
        TAG_NAME="${{ steps.add-tag.outputs.tag-name }}"

        PREV_TAG=$(git tag --list 'nightly-*' --sort=-creatordate | grep -v "^$TAG_NAME$" | head -n 1)

        if [ -z "$PREV_TAG" ]; then
          echo "No previous nightly tag found."
          echo "commits=No previous nightly tag found." >> "$GITHUB_OUTPUT"
        else
          COMMITS=$(git log --pretty=format:'- %h %s (%an)' "$PREV_TAG..$TAG_NAME")
          if [ -z "$COMMITS" ]; then
            COMMITS="No new commits since last nightly."
          fi

          echo "commits<<EOF" >> "$GITHUB_OUTPUT"
          echo "$COMMITS" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
        fi

    - name: Create a release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.add-tag.outputs.tag-name }}
        name: "Nigthly release: ${{ steps.add-tag.outputs.tag-name }}"
        body: |
          Release created during the nigthly workflow run.

          Commits since the last nightly:
          ${{ steps.commit-list.outputs.commits }}
        files: ./dist/*.whl
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}