name: "Install Verification"
description: "Install Verification"

inputs:
  release-artifacts-id:
    description: "Release artifacts"
    required: true



runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        artifact-ids: ${{ inputs.release-artifacts-id }}
        path: ${{ github.workspace }}/release
    - name: Display structure of downloaded files
      run: ls -R ${{ github.workspace }}/release
      shell: bash
