[build-system]
requires = ["wheel-stub"]
build-backend = "wheel_stub.buildapi"

[tool.wheel_stub]
index_url = "https://github.com/tenstorrent/tt-forge/releases/expanded_assets/ttmlir-0.1.0.dev20250606"

[tool.wheel_stub.extra]
stub_only = true
