name: Clean up release tests
description: Clean up release test workflow artifacts every day
on:
  workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Daily Releaser"
    types:
      - completed


jobs:
  clean-up-release-tests:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Delete drafts releases
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.TT_FORGE_RELEASER }}
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: tenstorrent
          token: ${{ secrets.GH_TOKEN }}
          image-names: "tt-*-slim"
          image-tags: "draft.tt-*.dev*"
          tag-selection: "tagged"
          dry-run: false
          cut-off: 1h
