name: Clean up release tests
on:
  workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Test Release RC/Stable Lifecycle"
      - "Test Nightly Releaser"
    types:
      - completed

env:
  disable: true

jobs:
  delete-drafts:
    runs-on: ubuntu-latest
    if: ${{ env.disable == 'false' }}
    steps:
      - name: Wait for workflow run Test Release RC/Stable Lifecycle
        uses: ./.github/actions/wait-workflow
        with:
          workflow_name: "Test Release RC/Stable Lifecycle"
      - name: Wait for workflow run Test Nightly Releaser
        uses: ./.github/actions/wait-workflow
        with:
          workflow_name: "Test Nightly Releaser"
      - name: Delete drafts releases
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ inputs.gha-token || secrets.GITHUB_TOKEN }}
      - name: Delete draft-*-release-*.* branches
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ github.token }}
          prefix: draft-*-release-*.*
