name: Clean up release tests
on:
  workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Test Release RC/Stable Lifecycle"
      - "Test Nightly Releaser"
    types:
      - completed


jobs:
  delete-drafts:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for workflow run Test Release RC/Stable Lifecycle
        uses: ./.github/actions/wait-workflow
        with:
          workflow_name: "Test Release RC/Stable Lifecycle"
      - name: Wait for workflow run Test Nightly Releaser
        uses: ./.github/actions/wait-workflow
        with:
          workflow_name: "Test Nightly Releaser"
      - name: Delete drafts releases
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.TT_FORGE_RELEASER }}
      - name: Delete draft-*-release-*.* branches
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.TT_FORGE_RELEASER }}
          prefix: draft-*-release-*.*
      - uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.TT_FORGE_RELEASER }}
