name: Create Version Branch releaser

on:
  workflow_dispatch:
    inputs:
      draft:
        description: 'Put PR in draft mode for testing'
        type: boolean
        default: true
        required: false
      repo:
        type: string
        description: 'Repo to release RC branch for e.g tenstorrent/tt-forge-fe'
        required: true
      workflow_allow_failed:
        description: 'Run even if workflow has failed'
        required: false
        type: boolean
        default: false
      commit:
        description: "Commit sha if you want to override release branch selection"
        required: false
        type: string
  workflow_call:
    inputs:
      draft:
        description: 'Put PR in draft mode for testing'
        type: boolean
        default: true
        required: false
      repo:
        type: string
        description: 'Repo to release RC branch for e.g tt-forge-fe'
        required: true
      workflow_allow_failed:
        description: 'Run even if workflow has failed'
        required: false
        type: boolean
        default: false
      commit:
        description: "Commit sha if you want to override release branch selection by last passing workflow"
        required: false
        type: string

jobs:
  create-version-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create Version branch - ${{ inputs.repo }}
      id: create-rc-branch
      uses: ./.github/actions/create-rc-branch
      with:
        repo: ${{ inputs.repo }}
        draft: ${{ inputs.draft || false }}
        workflow_allow_failed: ${{ inputs.workflow_allow_failed || false }}
        GH_TOKEN: ${{ secrets.TT_FORGE_RELEASER }}
