name: Nightly Release

on:
  workflow_call:
    inputs:
      draft:
        type: boolean
        default: true
        description: Put PR in draft mode for testing
      repo:
        type: string
        description: 'Repo to release e.g tt-forge-fe'
        required: true
        default: ''

permissions:
  pages: write
  id-token: write
  contents: write

jobs:
  get-version:
    outputs:
        tag: ${{ steps.version-tag.outputs.tag }}
        repo_short: ${{ steps.version-tag.outputs.repo_short }}

    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v4
    - name: version tag
      id: version-tag
      run: |
        source .version
        repo="${{ inputs.repo }}"
        repo_short="${repo#tenstorrent/}" >> $GITHUB_OUTPUT
        tag="${VERSION}.dev$(date +"%Y%m%d")"
        echo "tag=$tag" >> $GITHUB_OUTPUT
        echo "repo_short=$repo_short" >> $GITHUB_OUTPUT

  nightly-releaser:
    runs-on: ubuntu-latest
    needs: get-version
    env:
        GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v4
    - uses: mukunku/tag-exists-action@v1.6.0
      id: check-tag
      with:
        tag: "${{needs.get-version.outputs.repo_short }}-${{ needs.get-version.outputs.tag }}"

    - name: Release
      if: steps.check-tag.outputs.exists == 'false'
      uses: ./.github/actions/releaser
      with:
        draft: ${{ inputs.draft }}
        repo: ${{ inputs.repo }}
        release_type: 'nightly'
        branch: 'main'
        new_version_tag: ${{ needs.get-version.outputs.tag }}
        workflow_allow_failed: true
