name: On PR

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  actions: write

jobs:
  check-all-green:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: All checks passed
        run: echo "All required checks passed."
