name: Rc Release

on:
  schedule:
  - cron: '0 6 24 * *'
  workflow_dispatch:
    inputs:
      draft:
        type: boolean
        default: true
        description: Put PR in draft mode for testing
  push:


jobs:
  rc-release:
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: version tag
      id: version-tag
      run: |
        source .version
        echo "MAJOR=$MAJOR" >> $GITHUB_OUTPUT
        echo "MINOR=$MINOR" >> $GITHUB_OUTPUT
    - name: Create RC branch - tenstorrent/tt-forge-fe
      uses: ./.github/actions/create-rc-branch
      id: Create-RC-branch
      with:
        repo: tenstorrent/tt-forge-fe
        workflow: On nightly
        MAJOR: ${{ steps.version-tag.outputs.MAJOR }}
        MINOR: ${{ steps.version-tag.outputs.MINOR }}
