name: Release RC and Stable Branches

on:
  schedule:
  - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      draft:
        type: boolean
        default: true
        description: Put PR in draft mode for testing
  push:

jobs:
  rc-release:
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/get-release-branches
      id: get-release-branches
      with:
        repo: tenstorrent/tt-forge-fe
    - name: echo json
      run: echo ${{ steps.get-release-branches.outputs.json_results }}
