name: Check Repository Runners

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *' # Every 4 hours

jobs:
  list-runners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Find new offline runners in tt-forge
        id: tt-forge
        uses: ./.github/actions/offline-runners
        with:
          repo: tt-forge
          token: ${{ secrets.GH_TOKEN }}
      - name: Find new offline runners in tt-torch
        id: tt-torch
        uses: ./.github/actions/offline-runners
        with:
          repo: tt-torch
          token: ${{ secrets.GH_TOKEN }}
      - name: Find new offline runners in tt-xla
        id: tt-xla
        uses: ./.github/actions/offline-runners
        with:
          repo: tt-xla
          token: ${{ secrets.GH_TOKEN }}
      - name: Find new offline runners in tt-forge-fe
        id: tt-forge-fe
        uses: ./.github/actions/offline-runners
        with:
          repo: tt-forge-fe
          token: ${{ secrets.GH_TOKEN }}
      - name: Find new offline runners in tt-mlir
        id: tt-mlir
        uses: ./.github/actions/offline-runners
        with:
          repo: tt-mlir
          token: ${{ secrets.GH_TOKEN }}
      - name: Make report
        id: report
        shell: bash
        run: |
          output_file="output.txt"
          rm -f "$output_file"
          touch "$output_file"
          if [ -n "${{ steps.tt-forge.outputs.new_runners }}" ]; then
            echo "New offline runners in tt-forge: ${{ steps.tt-forge.outputs.new_runners }}" | tee -a "$output_file"
          fi
          if [ -n "${{ steps.tt-torch.outputs.new_runners }}" ]; then
            echo "New offline runners in tt-torch: ${{ steps.tt-torch.outputs.new_runners }}" | tee -a "$output_file"
          fi
          if [ -n "${{ steps.tt-xla.outputs.new_runners }}" ]; then
            echo "New offline runners in tt-xla: ${{ steps.tt-xla.outputs.new_runners }}" | tee -a "$output_file"
          fi
          if [ -n "${{ steps.tt-forge-fe.outputs.new_runners }}" ]; then
            echo "New offline runners in tt-forge-fe: ${{ steps.tt-forge-fe.outputs.new_runners }}" | tee -a "$output_file"
          fi
          if [ -n "${{ steps.tt-mlir.outputs.new_runners }}" ]; then
            echo "New offline runners in tt-mlir: ${{ steps.tt-mlir.outputs.new_runners }}" | tee -a "$output_file"
          fi
          if [ -s "$output_file" ]; then
            echo "send_msg={\"text\": $(cat "$output_file" | jq -Rs .)}" >> $GITHUB_OUTPUT
            echo "## Found new offline runners" >> $GITHUB_STEP_SUMMARY
            cat "$output_file" >> $GITHUB_STEP_SUMMARY
          fi
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.26.0
        if: steps.report.outputs.send_msg
        with:
          payload: ${{ steps.report.outputs.send_msg }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.OFFLINE_RUNNER_SLACK_WEBHOOK }}
