# Example workflow using the superset-api action
name: Superset API Example

on:
  push:

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required for checking out code

jobs:
  call_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Call Superset API
        id: api-call
        uses: ./.github/actions/superset-api
        with:
          query: 'benchmarks/last_measurement'
          query_params: >
            {
              "project": "tenstorrent/tt-metal",
              "ml_model_name": "tiiuae/falcon-7b-instruct",
              "batch_size": "32",
              "precision": "prefill[BFLOAT16-DRAM]_decode[BFLOAT16-L1_SHARDED]"
            }
            
      - name: Display Response
        run: |
          echo "API Response:"
          echo '${{ steps.api-call.outputs.response }}'