name: superset api

on:
  push:

jobs:
  api_call:
    runs-on: ubuntu-latest
    steps:
      - name: Call api
        run: |
          # Define variables for query parameters
          PROJECT="tenstorrent/tt-metal"
          ML_MODEL_NAME="tiiuae/falcon-7b-instruct"
          BATCH_SIZE="32"
          PRECISION="prefill[BFLOAT16-DRAM]_decode[BFLOAT16-L1_SHARDED]"
          
          # Make API call with variables and print response
          RESPONSE=$(curl -sSf "https://ftuxhxqka0.execute-api.us-east-2.amazonaws.com/api/v1/data_db_main/last_measurement?project=$PROJECT&ml_model_name=$ML_MODEL_NAME&batch_size=$BATCH_SIZE&precision=$PRECISION")
          
          # Print the response
          echo "API Response:"
          echo "$RESPONSE"