# Example workflow using the superset-api action
name: Superset API Example

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'ML model name'
        required: true
        default: 'tiiuae/falcon-7b-instruct'
      batch_size:
        description: 'Batch size'
        required: true
        default: '32'
      precision:
        description: 'Precision'
        required: true
        default: 'prefill[BFLOAT16-DRAM]_decode[BFLOAT16-L1_SHARDED]'

jobs:
  call_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install jq
        run: sudo apt-get install -y jq
          
      - name: Call Superset API
        id: api-call
        uses: ./.github/actions/superset-api
        with:
          query: 'benchmarks/last_measurement'
          query_params: >
            {
              "project": "tenstorrent/tt-metal",
              "ml_model_name": "${{ github.event.inputs.model_name }}",
              "batch_size": "${{ github.event.inputs.batch_size }}",
              "precision": "${{ github.event.inputs.precision }}"
            }
            
      - name: Display Response
        run: |
          echo "API Response:"
          echo '${{ steps.api-call.outputs.response }}' | jq .