name: superset api

on:
  push:

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required for checking out code

jobs:
  api_call:
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::533267429815:role/github-actions-api-gateway-role
          aws-region: us-east-2

      - name: Call api
        shell: bash
        run: |
          # Debug
          echo $AWS_DEFAULT_REGION | base64
          echo $AWS_REGION | base64
          echo $AWS_ACCESS_KEY_ID | base64
          echo $AWS_SECRET_ACCESS_KEY | base64
          echo $AWS_SESSION_TOKEN | base64

          # Define variables for query parameters
          PROJECT="tenstorrent/tt-metal"
          ML_MODEL_NAME="tiiuae/falcon-7b-instruct"
          BATCH_SIZE="32"
          PRECISION_RAW="prefill[BFLOAT16-DRAM]_decode[BFLOAT16-L1_SHARDED]"
          
          # URL encode the precision parameter (replace [ with %5B and ] with %5D)
          PRECISION=$(echo "$PRECISION_RAW" | sed 's/\[/%5B/g' | sed 's/\]/%5D/g')

          # echo attempt 1
          # TOKEN=$(aws sigv4-sign-request --region us-east-2 --service execute-api)
          # echo $TOKEN
          # echo $TOKEN | base64

          # # Make API call with variables and print response
          # RESPONSE=$(curl -X GET \
          #   -H "Authorization: Bearer $TOKEN" \
          #   "https://ftuxhxqka0.execute-api.us-east-2.amazonaws.com/api/v1/data_db_main/last_measurement?project=$PROJECT&ml_model_name=$ML_MODEL_NAME&batch_size=$BATCH_SIZE&precision=$PRECISION")
          
          # # Print the response
          # echo "API Response:"
          # echo "$RESPONSE"

          echo attempt 2
          RESPONSE=$(aws execute-api invoke --region us-east-2 \
            --path-template "/api/v1/data_db_main/last_measurement" \
            --query-string "project=$PROJECT&ml_model_name=$ML_MODEL_NAME&batch_size=$BATCH_SIZE&precision=$PRECISION" \
            --endpoint-url "https://ftuxhxqka0.execute-api.us-east-2.amazonaws.com" \
            /dev/null | jq -r '.authorization')
          
          # Print the response
          echo "API Response:"
          echo "$RESPONSE"

          echo attempt 3
          SIGNED_URL=$(aws execute-api get-presigned-url \
            --region us-east-2 \
            --http-method GET \
            --service-name execute-api \
            --endpoint-url "https://ftuxhxqka0.execute-api.us-east-2.amazonaws.com" \
            --path "/api/v1/data_db_main/last_measurement?project=$PROJECT&ml_model_name=$ML_MODEL_NAME&batch_size=$BATCH_SIZE&precision=$PRECISION")

          RESPONSE=$(curl "$SIGNED_URL")
