name: superset api

on:
  push:

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required for checking out code

env:
  AWS_REGION: us-east-2

jobs:
  api_call:
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::533267429815:role/github-actions-api-gateway-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Call api
        shell: bash
        env:
          PROJECT: "tenstorrent/tt-metal"
          ML_MODEL_NAME: "tiiuae/falcon-7b-instruct"
          BATCH_SIZE: "32"
          PRECISION_RAW: "prefill[BFLOAT16-DRAM]_decode[BFLOAT16-L1_SHARDED]"
        run: |
          # URL encode the precision parameter (replace [ with %5B and ] with %5D)
          PRECISION=$(echo "$PRECISION_RAW" | sed 's/\[/%5B/g' | sed 's/\]/%5D/g')

          pip install awscurl
          RESPONSE=$(awscurl \
            --region ${{ env.AWS_REGION }} \
            --service execute-api \
            "https://ftuxhxqka0.execute-api.${{ env.AWS_REGION }}.amazonaws.com/api/v1/data_db_main/last_measurement?project=$PROJECT&ml_model_name=$ML_MODEL_NAME&batch_size=$BATCH_SIZE&precision=$PRECISION")
          
          # Print the response
          echo "API Response:"
          echo "$RESPONSE"