name: Test Model Compatible Table

on:
  push:
    paths:
      - '.github/scripts/model-compatible-table/**'
  pull_request:
    paths:
      - '.github/scripts/model-compatible-table/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/scripts/model-compatible-table

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test-requirements.txt

    - name: Run tests
      run: |
        pytest -v test_main.py
