name: Test Nightly Releaser

on:
    push:
      branches:
        - main
      paths:
        - '.github/scripts/model-compatible-table/**'
        - '.github/scripts/wheel-version-updater.sh'
        - '.github/scripts/prune-nightly-branches.sh'
        - '.github/scripts/wait-on-tt-pypi-wheels.sh'
        - '.github/workflows/update-release.yml'
        - '.github/workflows/daily-releaser.yml'
        - '.github/workflows/release.yml'
        - '.github/workflows/nightly-release.yml'
        - '.github/workflows/create-version-branches.yml'
        - '.github/actions/create-rc-branch/**'
        - '.github/actions/docs-generator/**'
        - '.github/actions/find-workflow/**'
        - '.github/actions/get-release-branches/**'
        - '.github/actions/get-repos/**'
        - '.github/actions/build-release/**'
        - '.github/actions/uplift-artifacts/**'
        - '.github/actions/set-release-facts/**'
        - '.github/actions/install-verification/**'
        - '.github/actions/publish-tenstorrent-pypi/**'
        - '.github/actions/publish-github-release/**'
        - '.github/workflows/test-nightly-releaser.yml'
        - '.github/scripts/pyproject.toml'
        - '.github/scripts/template-setup.py'
    pull_request:
      types: [opened, synchronize, reopened, ready_for_review]
      branches: [ "main" ]
      paths:
        - '.github/scripts/model-compatible-table/**'
        - '.github/scripts/wheel-version-updater.sh'
        - '.github/scripts/prune-nightly-branches.sh'
        - '.github/scripts/wait-on-tt-pypi-wheels.sh'
        - '.github/workflows/update-release.yml'
        - '.github/workflows/daily-releaser.yml'
        - '.github/workflows/release.yml'
        - '.github/workflows/nightly-release.yml'
        - '.github/workflows/create-version-branches.yml'
        - '.github/actions/create-rc-branch/**'
        - '.github/actions/docs-generator/**'
        - '.github/actions/find-workflow/**'
        - '.github/actions/get-release-branches/**'
        - '.github/actions/get-repos/**'
        - '.github/actions/build-release/**'
        - '.github/actions/uplift-artifacts/**'
        - '.github/actions/set-release-facts/**'
        - '.github/actions/install-verification/**'
        - '.github/actions/publish-tenstorrent-pypi/**'
        - '.github/actions/publish-github-release/**'
        - '.github/workflows/test-nightly-releaser.yml'
        - '.github/scripts/pyproject.toml'
        - '.github/scripts/template-setup.py'
    workflow_dispatch:
      inputs:
        repo:
          description: 'Name of repo eg. tt-forge-fe'
          required: false
          default: ''
        draft:
          type: boolean
          default: true
          description: Put PR in draft mode for testing
        delete-drafts:
          type: boolean
          default: true
          description: Delete drafts

permissions:
  pages: write
  id-token: write
  contents: write
  actions: write
  packages: write
  attestations: write

jobs:
  test-daily-nightly-releaser:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/daily-releaser.yml
    secrets: inherit
    with:
      draft: true
      overwrite_releases: false
      repo: ${{ inputs.repo || '' }}
