name: Update RC and Stable Branches/Version

on:
  workflow_call:
    inputs:
      draft:
        type: boolean
        default: true
        description: Put PR in draft mode for testing
      repo:
        type: string
        description: 'Repo to release e.g tt-forge-fe'
        required: true
        default: ''
      overwrite_releases:
        type: boolean
        default: false
        description: Overwrite releases

permissions:
  pages: write
  id-token: write
  contents: write
  actions: write
  packages: write
  attestations: write

jobs:
  get-release-branches:
    outputs:
      json_results: ${{ steps.branches.outputs.json_results }}
      no_release_branches_or_new_commits: ${{ steps.branches.outputs.no_release_branches_or_new_commits }}
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ secrets.TT_FORGE_RELEASER }}
    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: ./.github/actions/set-release-facts
      id: set-release-facts
      with:
        repo: ${{ inputs.repo }}
        draft: ${{ inputs.draft }}
    - uses: ./.github/actions/get-release-branches
      id: branches
      with:
        repo: ${{ inputs.repo }}
        draft: ${{ inputs.draft || false }}
        repo_short: ${{ steps.set-release-facts.outputs.repo_short }}

  update-release-branches:
    if: ${{ needs.get-release-branches.outputs.no_release_branches_or_new_commits == 'false' }}
    needs: get-release-branches
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.get-release-branches.outputs.json_results) }}
    name: "${{ inputs.draft && 'Draft' || '' }}  ${{ matrix.repo_short }} ${{ matrix.release_type }} ${{ matrix.new_version_tag }}"
    secrets: inherit
    uses: ./.github/workflows/release.yml
    with:
      draft: ${{ inputs.draft || false }}
      repo: ${{ matrix.repo }}
      overwrite_releases: ${{ inputs.overwrite_releases || false }}
      release_type: ${{ matrix.release_type }}
      repo_short: ${{ matrix.repo_short }}
      branch: ${{ matrix.branch }}
      new_version_tag: ${{ matrix.new_version_tag }}
      latest_branch_commit: ${{ matrix.latest_branch_commit }}
      current_release_tag_commit: ${{ matrix.current_release_tag_commit }}
